[package]
name = "parallel"
version = "0.1.0"
authors = ["Izaan Siddiqi <izaans@hadean.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2" }
rayon = { version = "1.3" }
